// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjZAjKdaoGIbV2oBB2Hg42ZUUMTYeOzcM',
    appId: '1:1024928793079:web:626ec8242f7773cfe26ef2',
    messagingSenderId: '1024928793079',
    projectId: 'portfolio-917b2',
    authDomain: 'portfolio-917b2.firebaseapp.com',
    storageBucket: 'portfolio-917b2.firebasestorage.app',
    measurementId: 'G-3Q9L7MWF5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMzV7YcCGP_GdMHoNjbWppmsh9KLn4bDg',
    appId: '1:1024928793079:android:b4e2be5833b43d68e26ef2',
    messagingSenderId: '1024928793079',
    projectId: 'portfolio-917b2',
    storageBucket: 'portfolio-917b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv42maFnj7_m1rvTgVyM3wa3M1jtYXWOo',
    appId: '1:1024928793079:ios:0cad08711633a59be26ef2',
    messagingSenderId: '1024928793079',
    projectId: 'portfolio-917b2',
    storageBucket: 'portfolio-917b2.firebasestorage.app',
    iosBundleId: 'com.example.mdahy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv42maFnj7_m1rvTgVyM3wa3M1jtYXWOo',
    appId: '1:1024928793079:ios:0cad08711633a59be26ef2',
    messagingSenderId: '1024928793079',
    projectId: 'portfolio-917b2',
    storageBucket: 'portfolio-917b2.firebasestorage.app',
    iosBundleId: 'com.example.mdahy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjZAjKdaoGIbV2oBB2Hg42ZUUMTYeOzcM',
    appId: '1:1024928793079:web:083a9fd1ad870f51e26ef2',
    messagingSenderId: '1024928793079',
    projectId: 'portfolio-917b2',
    authDomain: 'portfolio-917b2.firebaseapp.com',
    storageBucket: 'portfolio-917b2.firebasestorage.app',
    measurementId: 'G-CXMQ3WP1V7',
  );
}
